// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneySplitterApi.Model;

#nullable disable

namespace MoneySplitterApi.Migrations
{
    [DbContext(typeof(MoneySplitterDbContext))]
    partial class MoneySplitterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("MoneySplitterApi.Model.User", b =>
                {
                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("guid");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
